export default {
  qAChaiFenP: 'Prompt for QA Split',
  zuiDaXiangYingChang: 'Max Token',
  wenDu: 'Temperature',
  QAChaiFenGaoJiPeiZhi: 'QA Split Advanced Configuration',
  moXingPeiZhi: 'Model Configuration',
  QAQuChongPeiZhi: 'QA reconfiguration',
  xiangLiangHuaMoXing: 'Vectorized model',
  xiangSiDuYuZhi: 'Similarity threshold',
  duiChaiFenJieGuoJinXingQuChongChuLi: 'Perform deduplication on the split results',
  shuaXin: 'Refresh',
  shouQi: 'Fold',
  zhanKai: 'Unfold',
  chuLiShiBai: 'Failed to process',
  chuLiChengGong: 'Processed successfully',
  chuLiZhong: 'Processing',
  weiChuLi: 'Unprocessed',
  chongShi: 'Try again',
  gaoJiPeiZhi: 'Advanced Configuration ',
  moXing: 'Model:',
  fenDuanChangDu: 'chunk size:',
  fenDuanChongFuChangDu: 'chunk overlap:',
  chuLiHou: 'Processed',
  wenJianMing: 'File Name',
  chuLiQian: 'Before processing',
  chaiFenChuLi: 'Split',
  riZhi: 'Log',
  queRenShanChuRen: 'Are you sure to delete the task?',
  shanChu: 'Delete',
  jiChuXinXi: 'Base Info',
  shanChuRenWuShi: 'Failed to delete the task',
  shanChuRenWuCheng: 'Deleted successfully',
  zheShiYiGeMing: 'This is a name',
  haoShi: 'Time spent：',
  chaKanRiZhi: 'View Logs',
  shuJuChuLiXiang: 'Data Processing Details',
  zanWuShuJu: 'No data available',
  shuJuChuLi: 'Data processing',
  wenJianChuLiZhuangTai: 'File processing status',
  huoQuXiangXiXin: 'Failed to get the details',
  shiBai: 'Failed',
  chuLiWanCheng: 'Processed',
  kaiShiShiJian: 'Start Time',
  wanChengShiJian: 'Completion time',
  chuangJianRen: 'Creator',
  chuLiHouShuJu: 'Processed Dataset:',
  chuLiQianShuJu: 'Dataset before Processing:',
  qAWenBen: 'QA Text',
  puTongWenBen: 'Normal ext',
  wenJianLeiXing: 'File Type',
  duiSOUR:
    'Processed {val1} files to {val2}, the following is the sample preview of the processing effect, but not all samples.',
  duiSOUR2: 'Processed {val1} files to {val2}, current progress: ',
  duiSOUR3: 'Processed {val1} files to {val2}',
  fileStatusCount:
    'There are a total of <span style="font-weight:700;">{total}</span> files. Among the <span style="font-weight:700;color:#1677ff;">{doing}</span> files processed, <span style="font-weight:700;color:#5cb85c;">{success}</span>  files were successfully processed, <span style="font-weight:700;color:rgba(0,0,0,.25);">{not_start}</span>  files were pending, and <span style="font-weight:700;color:#f85a5a;">{fail}</span> files failed to be processed',
};
