export default {
  yinYong: '引用：',
  yeMa: '页码',
  yuanWen: '原文',
  biaoTi: '标题',
  xiangSiDu: '相似度:',
  zhiShiKu: '知识库',
  yinYongShuJu: '引用数据',
  qingShuRuWenTi: '请输入问题，可通过 shift+回车 换行',
  faSong: '发送',
  zanWeiGuanLianMo: '暂未关联模型服务，请先关联模型服务再进行对话',
  huanXing: '换行',
  faSong2: '发送 /',
  tiaoShangXiaWen: '{val1} 条上下文',
  qingQiuChuCuo: '请求出错',
  xiTongYiChangQing: '系统异常，请稍后重试',
  ninHaoWoShiA: '##### 您好，我是{val1}',
  jinTian: '今天',
  shanChuDuiHua: '删除对话',
  queDing: '确定',
  queDingShanChuDui: '确定删除对话吗?',
  quXiao: '取消',
  xinJianDuiHua: '新建对话',
  shanChuChengGong: '删除成功',
  tingZhi: '停止',
  bianJiShuJu: '编辑数据',
  beiSouSuoDe: '被搜索的内容（Q）',
  QingShuRuBeiSouSuoDe: '请输入被搜索的内容（Q）',
  oneDangQian:
    '1. 当前数据为被向量化的内容，该部分内容的质量决定了在对话时，能否高效、准确的找到合适的知识；2. 此处内容一般是搜索的问题，最多可输入 2000 字。此处内容一般是搜索匹配的内容，最多可输入 2000 字。',
  piPeiNeiRong: '匹配内容（A）',
  qingShuRuPiPeiNeiRong: '请输入匹配内容（A））',
  ciChu: '此处内容一般是搜索匹配的内容，最多可输入 2000 字。',
  ciChuTian: '此处填写 QA 内容引用的源文件名称。',
  ciChuTianYuanWen: '此处填写 QA 内容引用的原文段落所在页码。',
  yuanWenDuanLuo: '原文段落',
  ciChuYuanWen: '此处填写 QA 引用的原文段落，最多可输入 2000 字。',
  wenJianMing: '文件名称',
  bianJiShuJuShiBai: '编辑数据失败',
  bianJiShuJuChengGong: '编辑数据成功',
  VectorStoreIsNotReady: '向量数据库没有就绪',
  EmbedderIsNotReady: 'embedder 服务没有就绪',
  KnowledgeBaseNotReady: '知识库未就绪',
  LLMNotReady: '模型服务没有就绪',
  ConfigError: '应用配置错误',
};
