export default {
  yinYong: '引用：',
  yeMa: '页码:',
  yuanWen: '原文',
  biaoTi: '标题',
  xiangSiDu: '相似度:',
  zhiShiKu: '知识库',
  yinYongShuJu: '引用数据',
  qingShuRuWenTi: '请输入问题，可通过 shift+回车 换行',
  faSong: '发送',
  zanWeiGuanLianMo: '暂未关联模型服务，请先关联模型服务再进行对话',
  huanXing: '换行',
  faSong2: '发送 /',
  tiaoShangXiaWen: '{val1} 条上下文',
  qingQiuChuCuo: '请求出错',
  xiTongYiChangQing: '系统异常，请稍后重试',
  ninHaoWoShiA: '##### 您好，我是{val1}',
  jinTian: '今天',
  shanChuDuiHua: '删除对话',
  queDing: '确定',
  queDingShanChuDui: '确定删除对话吗?',
  quXiao: '取消',
  xinJianDuiHua: '新建对话',
  shanChuChengGong: '删除成功',
  tingZhi: '停止',
};
