export default {
  qAChaiFenP: 'QA 拆分 Prompt',
  zuiDaXiangYingChang: '最大 Token',
  wenDu: '温度',
  QAChaiFenGaoJiPeiZhi: 'QA拆分高级配置',
  moXingPeiZhi: '模型配置',
  QAQuChongPeiZhi: 'QA 去重配置',
  xiangLiangHuaMoXing: '向量化模型',
  xiangSiDuYuZhi: '相似度阈值',
  duiChaiFenJieGuoJinXingQuChongChuLi: '对拆分结果进行去重处理',
  shuaXin: '刷新',
  shouQi: '收起',
  zhanKai: '展开',
  chuLiShiBai: '处理失败',
  chuLiChengGong: '处理成功',
  chuLiZhong: '处理中',
  weiChuLi: '未处理',
  chongShi: '重试',
  gaoJiPeiZhi: '高级配置',
  moXing: '模型:',
  fenDuanChangDu: '分段长度：',
  fenDuanChongFuChangDu: '分段重叠长度：',
  chuLiHou: '处理后',
  wenJianMing: '文件名',
  chuLiQian: '处理前',
  chaiFenChuLi: '拆分处理',
  riZhi: '日志',
  queRenShanChuRen: '确认删除任务？',
  shanChu: '删除',
  jiChuXinXi: '基础信息',
  shanChuRenWuShi: '删除任务失败',
  shanChuRenWuCheng: '删除任务成功',
  zheShiYiGeMing: '这是一个名',
  haoShi: '耗时：',
  chaKanRiZhi: '查看日志',
  shuJuChuLiXiang: '数据处理详情',
  zanWuShuJu: '暂无数据',
  shuJuChuLi: '数据处理',
  wenJianChuLiZhuangTai: '文件处理状态',
  huoQuXiangXiXin: '获取详细信息失败',
  shiBai: '失败',
  chuLiWanCheng: '处理完成',
  kaiShiShiJian: '开始时间',
  wanChengShiJian: '完成时间',
  chuangJianRen: '创建人',
  chuLiHouShuJu: '处理后数据集',
  chuLiQianShuJu: '处理前数据集',
  qAWenBen: 'QA文本',
  puTongWenBen: '普通文本',
  wenJianLeiXing: '文件类型',
  duiSOUR: '对 {val1} 个文件进行了 {val2}，以下内容为处理效果抽样预览，并非全部内容',
  duiSOUR2: '对 {val1} 个文件进行了 {val2}，处理进度：',
  duiSOUR3: '对 {val1} 个文件进行了 {val2}。',
  fileStatusCount:
    '共有 <span style="font-weight:700;">{total}</span> 个文件，<span style="font-weight:700;color:#1677ff;">{doing}</span> 个文件处理中，<span style="font-weight:700;color:#5cb85c;">{success}</span>  个文件处理成功，<span style="font-weight:700;color:rgba(0,0,0,.25);">{not_start}</span> 个文件待处理， <span style="font-weight:700;color:#f85a5a;">{fail}</span> 个文件处理失败',
};
