export default {
  qAChaiFenP: 'QA 拆分 Prompt',
  zuiDaXiangYingChang: '最大响应长度',
  wenDu: '温度',
  moXingPeiZhi: '模型配置',
  shuaXin: '刷新',
  shouQi: '收起',
  zhanKai: '展开',
  chuLiShiBai: '处理失败',
  chuLiChengGong: '处理成功',
  chuLiZhong: '处理中',
  weiChuLi: '未处理',
  gaoJiPeiZhi: '高级配置',
  moXing: '模型:',
  chuLiHou: '处理后',
  wenJianMing: '文件名',
  chuLiQian: '处理前',
  chaiFenChuLi: '拆分处理',
  riZhi: '日志',
  queRenShanChuRen: '确认删除任务？',
  shanChu: '删除',
  shanChuRenWuShi: '删除任务失败',
  shanChuRenWuCheng: '删除任务成功',
  zheShiYiGeMing: '这是一个名',
  gengXinShiJian: '更新时间：',
  chaKanRiZhi: '查看日志',
  shuJuChuLiXiang: '数据处理详情',
  zanWuShuJu: '暂无数据',
  shuJuChuLi: '数据处理',
  xiangXiXinXi: '详细信息',
  huoQuXiangXiXin: '获取详细信息失败',
  shiBai: '失败',
  chuLiWanCheng: '处理完成',
  chuangJianShiJian: '创建时间',
  chuangJianRen: '创建人',
  chuLiHouShuJu: '处理后数据集',
  chuLiQianShuJu: '处理前数据集',
  qAWenBen: 'QA文本',
  puTongWenBen: '普通文本',
  wenJianLeiXing: '文件类型',
  duiSOUR: '对 {val1} 个文件进行了{val2}，以下内容为处理效果抽样预览，并非全部内容',
  duiSOUR2: '对 {val1} 个文件进行了{val2}，处理进度：',
  duiSOUR3: '对 {val1} 个文件进行了{val2}。',
};
