export default {
  yinYong: 'Reference:',
  yeMa: 'Page',
  yuanWen: 'The Original',
  biaoTi: 'Title',
  xiangSiDu: 'Similarity:',
  zhiShiKu: 'Knowledge Base',
  yinYongShuJu: 'Reference Data',
  qingShuRuWenTi: 'Input your question, use shift+enter to wrap the line',
  faSong: 'Send',
  zanWeiGuanLianMo:
    'No associated model service, associate the model service before proceeding with the conversation',
  huanXing: 'Line Break',
  faSong2: 'Send /',
  tiaoShangXiaWen: '{val1} context',
  qingQiuChuCuo: 'Request error',
  xiTongYiChangQing: 'System error, try again later',
  ninHaoWoShiA: '##### Hello, I am {val1}',
  jinTian: 'Today',
  shanChuDuiHua: 'Delete conversation',
  queDing: 'OK',
  queDingShanChuDui: 'Are you sure to delete the conversation?',
  quXiao: 'Cancel',
  xinJianDuiHua: 'Create new conversation',
  shanChuChengGong: 'Deleted successfully',
  tingZhi: 'Stop',
};
