export default {
  qAChaiFenP: 'Prompt for QA Split',
  zuiDaXiangYingChang: 'Max Token',
  wenDu: 'Temperature',
  moXingGaoJiPeiZhi: 'Advanced Model Configuration',
  moXingPeiZhi: 'Model Configuration',
  QAQuChongPeiZhi: 'QA reconfiguration',
  xiangLiangHuaMoXing: 'Vectorized model',
  xiangSiDuYuZhi: 'Similarity threshold',
  duiChaiFenJieGuoJinXingQuChongChuLi: 'Perform deduplication on the split results',
  shuaXin: 'Refresh',
  shouQi: 'Fold',
  zhanKai: 'Unfold',
  chuLiShiBai: 'Failed to process',
  chuLiChengGong: 'Processed successfully',
  chuLiZhong: 'Processing',
  weiChuLi: 'Unprocessed',
  gaoJiPeiZhi: 'Advanced Configuration ',
  moXing: 'Model:',
  chuLiHou: 'Processed',
  wenJianMing: 'File Name',
  chuLiQian: 'Before processing',
  chaiFenChuLi: 'Split',
  riZhi: 'Log',
  queRenShanChuRen: 'Are you sure to delete the task?',
  shanChu: 'Delete',
  shanChuRenWuShi: 'Failed to delete the task',
  shanChuRenWuCheng: 'Deleted successfully',
  zheShiYiGeMing: 'This is a name',
  gengXinShiJian: 'Update time：',
  chaKanRiZhi: 'View Logs',
  shuJuChuLiXiang: 'Data Processing Details',
  zanWuShuJu: 'No data available',
  shuJuChuLi: 'Data processing',
  xiangXiXinXi: 'Details',
  huoQuXiangXiXin: 'Failed to get the details',
  shiBai: 'Failed',
  chuLiWanCheng: 'Processed',
  chuangJianShiJian: 'Creation Time',
  chuangJianRen: 'Creator',
  chuLiHouShuJu: 'Processed Dataset',
  chuLiQianShuJu: 'Dataset before Processing',
  qAWenBen: 'QA Text',
  puTongWenBen: 'Normal ext',
  wenJianLeiXing: 'File Type',
  duiSOUR:
    'Processed {val1} files to {val2}, the following is the sample preview of the processing effect, but not all samples.',
  duiSOUR2: 'Processed {val1} files to {val2}, current progress: ',
  duiSOUR3: 'Processed {val1} files to {val2}',
};
